stages:
    - install

install-traefik:
    stage: install
    tags:
        - shell  
    before_script:
        - export KUBECONFIG=$KUBE_CONFIG
    script:
        - helm repo add traefik https://traefik.github.io/charts    
        - helm repo update
        - kubectl create ns traefik-v2
        - helm install --namespace=traefik-v2 \traefik traefik/traefik
        - kubectl port-forward $(kubectl get pods --selector "app.kubernetes.io/name=traefik" --output=name) -n traefik-v2 9000:9000 -n traefik-v2
