apiVersion: v1
kind: Config
clusters:
- name: "harvester-cluster"
  cluster:
    server: "https://rancher-dev.coe.com/k8s/clusters/c-m-xlcrnnqj"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlEakRDQ\
      0FuU2dBd0lCQWdJUUhkdFVYc2tQakoxSkJsUjJWNitxOURBTkJna3Foa2lHOXcwQkFRc0ZBREJGD\
      QpNUk13RVFZS0NaSW1pWlB5TEdRQkdSWURZMjl0TVJNd0VRWUtDWkltaVpQeUxHUUJHUllEWTI5b\
      E1Sa3dGd1lEDQpWUVFERXhCamIyVXRRMEV0UVVRdFVFUkRMVU5CTUI0WERUSXhNRFV3TkRBMk16R\
      XpNMW9YRFRNeE1EVXdOREEyDQpOREV6TTFvd1JURVRNQkVHQ2dtU0pvbVQ4aXhrQVJrV0EyTnZiV\
      EVUTUJFR0NnbVNKb21UOGl4a0FSa1dBMk52DQpaVEVaTUJjR0ExVUVBeE1RWTI5bExVTkJMVUZFT\
      FZCRVF5MURRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEDQpnZ0VQQURDQ0FRb0NnZ0VCQUtBd\
      UhZWExoelJkYS9zSmZzeGl2WVUyTWJ0Nm81cmlxdmxUa3pMVmFmNVUvdk9mDQo2dDY1MGVqNXhRO\
      DFPNE0wZ01OYlFaUWNRNzEzWFYzbElDNzZPRU5mRDNkNEtsWU5HY0VMNHRWOGpsb2Jyek1ZDQpqN\
      28ybEpnc1JZN09CeHRUTHJXQ2YxditZQXlzZWpHNnEwRkNPTTFReWlicW1jYkZEUzBhZFZpRXh0e\
      XgwdzVlDQpTcWNyTkNDRng2S3A3VDkvZnJock9IaTF4eG5sTEQwVGdhSjFxUHVhTHdvYjhuZHR6R\
      npabENmNERzUlg1allpDQpIVlNWbDk3cVhDRmJLSWNSZ0Q2SFFmUnpKSElGaUdWYk03djVaSlFWW\
      WxHbFAweWNGMGxUdnQ3YS8zMno3Y3VrDQpmc2FoUVNzczJRMGZnRlJXVW45ZmVGUU9IUlVNY2wxV\
      2FwS1BpOWNDQXdFQUFhTjRNSFl3Q3dZRFZSMFBCQVFEDQpBZ0dHTUE4R0ExVWRFd0VCL3dRRk1BT\
      UJBZjh3SFFZRFZSME9CQllFRkhrK3RORm4vVzhnZTQ3bmZlVm9BZ1MwDQo0SE1DTUJJR0NTc0dBU\
      VFCZ2pjVkFRUUZBZ01CQUFFd0l3WUpLd1lCQkFHQ054VUNCQllFRlA4VHUrTktnY3ZnDQpSTDVXd\
      i9QK0E3NlZBTUx6TUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDVEFtejVKejRGdEo3ajBNL2Rzd\
      DV4DQptdHUzQVZINGhRQlRXa2lUSnF1Q05hNFhTeHlna0p2M3c2T0tZR28xeG9UWDlxVHJybFdGN\
      zVMMk5qYXZtK2RmDQo4dkRzQUtCU0NaeHlrdHZkaVYxTmg2WWkxWmZEVWRFa1h6NlhLemFHSURtM\
      jlqRHRXZjUrVVhoQUUzNFZLaXFWDQpHcWJpUm11UnBPSEpVaUVHN3ZGeWozSk1pSWtjaFNuZTVrS\
      kVaZ1Q5V2xPanRUejhScVNybUE4bmVIanNybUdWDQpOdFZZRWU5UVdLY283dGJqT25lRjNlMzUzd\
      VB1L2hPNkpiTlpCMmJ0T3JkUmtQNm1uVnY3Z3RveE9ReVRJcFhiDQp5M3ZldW9LTituVkMzZEp6V\
      FV6MzdFZlZrdndoYVFBWmdIS2dROFN3MVE1WWowZG1EUHo5SzczRXhaMUV1ellQDQotLS0tLUVOR\
      CBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "harvester-cluster"
  user:
    token: "kubeconfig-user-78ngmlq7mv:cllbhqlx667tt2h776xbm7tzqfbmxr276kk24vc8tbf528vtwgxnkm"


contexts:
- name: "harvester-cluster"
  context:
    user: "harvester-cluster"
    cluster: "harvester-cluster"

current-context: "harvester-cluster"
