apiVersion: v1
kind: Config
clusters:
- name: "local"
  cluster:
    server: "https://192.168.30.139/k8s/clusters/local"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJwekNDQ\
      VUyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQTdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1Sc3dHUVlEVlFRREV4SmtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRXdIa\
      GNOTWpJdwpNVEl6TURrd09EVTRXaGNOTXpJd01USXhNRGt3T0RVNFdqQTdNUnd3R2dZRFZRUUtFe\
      E5rZVc1aGJXbGpiR2x6CmRHVnVaWEl0YjNKbk1Sc3dHUVlEVlFRREV4SmtlVzVoYldsamJHbHpkR\
      1Z1WlhJdFkyRXdXVEFUQmdjcWhrak8KUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVExbE9pUkx0QkhkV\
      E9RNHA0dGg3T3VGUkNSTXFWNHZhcHdyQnRoMkZVYwpmeXVkY1VpWVJESW5IRUlUWmdwQTJNYVRxW\
      m1NMVhIUFJrd0tOWDYxcmJ5WG8wSXdRREFPQmdOVkhROEJBZjhFCkJBTUNBcVF3RHdZRFZSMFRBU\
      UgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVaUhTUDd1YjAwdkNyNE1IQmErYkEKRE1KT0QvZ3dDZ\
      1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBTEZpN2hzY3lCaXo4V3J5Z2ZnVnNEMUFhRkdKcSthTQpWW\
      G5wR2tKTUl6N2JBaUJxbjVmNml4cnBNeFduRC82UEVWQU9pN3pKc3dJVVpnWUN2bXRtVWRBTUZBP\
      T0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="

users:
- name: "local"
  user:
    token: "kubeconfig-user-fpcnqj7z2g:nvgfxnjmglrv66fznkbpvl9v9n2w9rw2n64rwvkzlpj9zzqxwsfnwb"


contexts:
- name: "local"
  context:
    user: "local"
    cluster: "local"

current-context: "local"
