version: 1
config:
  - type: physical
    name: enp1s0
    subnets:
      - type: static
        address: 10.0.100.148/24
        gateway: 10.0.100.1
  - type: nameserver
    address:
      - 192.168.30.131
    search:
      - coe.com
